### ISSUE TITLE
App cannot be used from the invoicing.saltares.com domain

### ISSUE THREAD

**Issue by TomClarkson** [dsaltares/invoicing#274]
Hi there, thanks for making the project open source.

I am getting the following error when I try to use the deployed app

Access to fetch at 'https://app.beetbill.com/api/trpc/getInvoices?batch=1&input=%7B%7D' from origin 'https://invoicing.saltares.com' has been blocked by CORS policy

**Comment by dsaltares** [comment]
Thanks for reporting @TomClarkson.
Initially, the domain was `invoicing.saltares.com`, but I now migrated it to `app.beetbill.com`. You should only access the app from https://app.beetbill.com from now on. I have made `invoicing.saltares.com` unavailable and updated the repo URL.

Out of curiosity, how did you find this project?
